name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  linux-x86_64:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Git
        run: echo "${{ secrets.PAT }}" | gh auth login --with-token

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run build with Gradle Wrapper
        run: ./gradlew build
  windows-x86_64:
    runs-on: windows-2019
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Git
        run: echo "${{ secrets.PAT }}" | gh auth login --with-token

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run build with Gradle Wrapper
        run: ./gradlew build
  macosx-x86_64:
    runs-on: macos-13
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Git
        run: echo "${{ secrets.PAT }}" | gh auth login --with-token

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run build with Gradle Wrapper
        run: ./gradlew build